version: 2.1
orbs:
  node: circleci/node@2.0.2
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    steps:
      - checkout
      - node/install-npm
      - node/install-packages
      - run: npm install
      - run: npm run converage
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
  build:
    jobs:
      - build
