version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@1.1.1
executors:
  test-executor:
    docker:
      - image: cimg/node:lts
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: tests
jobs:
  test:
    executor: test-executor
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/gocommerce/node_modules
      - run: npm run test
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
  test:
    jobs:
      - test
