version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 12.18.3
      - run: yarn converage
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
  build:
    jobs:
      - build
