version: 2.1
orbs:
  node: circleci/node@2.0.2
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
  build:
    jobs:
      - build
